services:
  # --- DATABASE POSTGRESQL ---
  db:
    image: postgres:15-alpine
    container_name: kasir_db_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahasia
      POSTGRES_DB: db_kasir_laptop
    ports:
      - "5433:5432" # Akses dari luar lewat 5433, di dalam tetap 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- APLIKASI NEXT.JS ---
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasir_web_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      # PENTING: DATABASE_URL diarahkan ke service 'db' di atas
      DATABASE_URL: "postgresql://postgres:rahasia@db:5432/db_kasir_laptop"
      AUTH_SECRET: "elite-gear-super-secret-key-2026"
      NEXTAUTH_URL: "http://192.168.0.139:3000"
    depends_on:
      - db

volumes:
  pgdata: